### PR TITLE
Create TeamStats Class & Refactor

### PR DESCRIPTION
**Pull request by hamouj**
This PR will:
-Create the TeamStats class which inherits from the StatData class
-Refactor the TeamStats methods
-Update TeamStats tests to include tests for helper methods
-Update the methods within the StatTracker class

### CODE REVIEW

**Comment by radsy207** [comment]
Looks good!

**Review by NickolasAM — APPROVED** [review]
We had really great questions. I enjoyed hearing everybody's thoughts and what came to mind when thinking about them. Great job!

**Comment by eelektra** [comment]
Looks good to me!

**Review by davejm8 — APPROVED** [review]
Nice job with the team stats refactor

**Pull request merged**
