### PR TITLE
Season Methods Refactor

### PR DESCRIPTION
**Pull request by davejm8**
added stat_data parent with spec file and using it's inheritance on season_stats and stat_tracker

### CODE REVIEW

**Review by hamouj — APPROVED** [review]
Ran everything and all tests pass.
Noted the creation of the StatData superclass.

**Review by NickolasAM — APPROVED** [review]
Looks great!

**Comment by davejm8** [comment]
Send it!

**Comment by eelektra** [comment]
Passed rspec and spec harness tests.  Merging

**Pull request merged**
