### PR TITLE
LeagueStats reorg and refactor

### PR DESCRIPTION
**Pull request by eelektra**
Created LeagueStats class, refactored large methods, and ensured at least one test was created for each method.  In addition, all tests pass rspec and spec harness.

### CODE REVIEW

**Review by hamouj — APPROVED** [review]
All methods have tests and all tests pass!
The coverage folder was added in this, so we may have

**Review by NickolasAM — APPROVED** [review]
Looks good, great job on refactoring!

**Comment by davejm8** [comment]
Looks good!

**Review by davejm8 — APPROVED** [review]
Excellent!

**Pull request merged**
