### PR TITLE
Game Statistics Methods & Tests

### PR DESCRIPTION
**Pull request by hamouj**
Includes:
-All game statistic methods and helper methods
-Test for each game statistic and helper methods
-Updated sample data sets (games_spec.csv and game_teams_spec.csv)

### CODE REVIEW

**Comment by davejm8** [comment]
Nice! Noted that data files have been moved around. I ran it on my end and everything passes. Merge?

**Review by NickolasAM — APPROVED** [review]
Looks great!  On to the next one!

**Review by eelektra — CHANGES_REQUESTED** [review]
In the stat_tracker_spec file, game_teams.csv needs to be changed to game_teams_spec.csv.
Remove the extra lines and commented out method.

**Review by eelektra — APPROVED** [review]
Changes look good.

**Pull request merged**
